// "use client";

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";
// import { metadata } from "./metadata";
// import SessionWrapper from "./components/sessionwrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionProvider>{children}</SessionProvider>
//       </body>
//     </html>
//   );
// }


// app/layout.js
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { metadata } from "./metadata"; // Import metadata
import SessionWrapper from "./components/sessionwrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper>{children}</SessionWrapper> {/* Wrap only children */}
      </body>
    </html>
  );
}
